routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');


// Route advisoryapp
Route::group(['middleware' => ['auth']], function () {
    Route::resource('listing','ListingController');
});

app/Listing.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;

class Listing extends Model
{
    //
    protected $fillable = [
        'list_name',
        'distance',
        'user_id'
    ];


    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/User.php
<?php

namespace App;

use App\Listing;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','type',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function listing(){
        return $this->hasMany(Listing::class);
    }

    public function getJWTIdentifier()
        {
            return $this->getKey();
        }
        public function getJWTCustomClaims()
        {
            return [];
        }
}

app/Http/Controllers/ApiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use JWTAuth;
use App\Listing;
use App\User;
use Tymon\JWTAuth\Exceptions\JWTException;

class ApiController extends Controller
{
    //
    public function login(Request $request)
    {
        $credentials = $request->only('email', 'password');

        $user_id = User::where('email', $request->email)->pluck('id');

        try {
            // attempt to verify the credentials and create a token for the user
            if (! $token = JWTAuth::attempt($credentials)) {
                return response()->json(['success' => false, 'error' => 'We cant find an account with this credentials. Please make sure you entered the right information and you have verified your email address.'], 404);
            }
        } catch (JWTException $e) {
            // something went wrong whilst attempting to encode the token
            return response()->json(['success' => false, 'error' => 'Failed to login, please try again.'], 500);
        }
        // all good so return the token
        User::where('id',$user_id)->update([
                'token' => $token
            ]);

        return response()->json(['success' => true, 'token' => $token , 'id' => $user_id , 'status' => [ 'code' => 200 , 'message' => 'Access Granted']]);
    }

    public function show(Request $request)
    {
        $listing = Listing::where('user_id', auth()->user()->id)->get(['id','list_name','distance']);

        if (! $listing->count() == 0) {
            return response()->json(['listing' => $listing,'status' => [ 'code' => 200, 'message' => 'Listing successfully retrieved']]);
        }
        return response()->json(['success' => false, 'error' => 'We cant find data with this credentials. Please make sure you entered the right information.'], 404);

    }

    public function logout()
    {
        try {
            JWTAuth::invalidate(JWTAuth::getToken());
            User::where('token',JWTAuth::getToken())->update([ 'token' => null ]);
            return response()->json(['success' => true, 'message'=> "You have successfully logged out."]);
        } catch (JWTException $e) {
            // something went wrong whilst attempting to encode the token
            return response()->json(['success' => false, 'error' => 'Failed to logout, please try again.'], 500);
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ListingController.php
<?php

namespace App\Http\Controllers;

use App\Listing;
use App\User;
use Auth;
use Illuminate\Http\Request;

class ListingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // if (Auth::user()->type == 'A') {
        //     $lists = Listing::paginate(10);
        // } else {
        //     $lists = Listing::where('user_id',2)->paginate(10);
        // }
        $lists = Listing::paginate(10);

        return view('admin.index',compact('lists'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::get();

        return view('admin.create',compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'list_name' => 'required|max:255',
            'distance'  => 'required|numeric|between:0,999.99',
            'user_id'   => 'required'
        ]);

        Listing::create($request->all());

        return redirect()->route('listing.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Listing  $listing
     * @return \Illuminate\Http\Response
     */
    public function show(Listing $listing)
    {
        //
        return view('admin.show',compact('listing'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Listing  $listing
     * @return \Illuminate\Http\Response
     */
    public function edit(Listing $listing)
    {
        $users = User::get();

        return view('admin.edit',compact('listing','users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Listing  $listing
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Listing $listing)
    {
        //
        $this->validate($request,[
            'list_name' => 'required|max:255',
            'distance'  => 'required|numeric|between:0,999.99'
        ]);

        Listing::where('id',$listing->id)->update($request->except('_token','_method'));

        return redirect()->route('listing.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Listing  $listing
     * @return \Illuminate\Http\Response
     */
    public function destroy(Listing $listing)
    {
        //
        Listing::find($listing->id)->delete();

        return redirect()->route('listing.index');
    }
}

resources/views/admin/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Create new list</h2><br>
        <div class="row">
            <form action="{{ route('listing.store')}}" method="post" enctype="multipart/form-data">
                @csrf
              <div class="form-group">
                <label for="exampleInputEmail1">List Name</label>
                <input name="list_name" type="text" class="form-control" id="list_name" aria-describedby="emailHelp" placeholder="Enter restaurant name" required>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Distance</label>
                <input name="distance" type="number" step=".01" class="form-control" id="distance" placeholder="Distance" required>
              </div>
              <div class="form-group">
                <select class="" name="user_id">
                    <option value="" selected disabled>Select</option>
                    @foreach ($users as $user)
                        <option value="{{ $user->id }}">{{ $user->name }}</option>
                    @endforeach
                </select>
              </div>
              <a href="{{ route('listing.index')}}" class="btn btn-primary">Back</a>
              <button type="submit" class="btn btn-success">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Edit list</h2><br>
        <div class="row">
            <form action="{{ route('listing.update',$listing)}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
              <div class="form-group">
                <label for="exampleInputEmail1">List Name</label>
                <input name="list_name" type="text" class="form-control" id="list_name" value="{{ $listing->list_name }}" placeholder="Enter restaurant name">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Distance</label>
                <input name="distance" type="number" class="form-control" value="{{ $listing->distance }}" id="distance" placeholder="Distance">
              </div>
              <div class="form-group">
                <select class="" name="">
                    @foreach ($users as $user)
                        <option value="{{ $user->id }}" {{($listing->user->id == $user->id ? 'selected' : '')}}>{{ $user->name }}</option>
                    @endforeach
                </select>
              </div>
              <a href="{{ route('listing.index')}}" class="btn btn-primary">Back</a>
              <button type="submit" class="btn btn-success">Update</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>List of Restaurant</h1><br>
        @if(Auth::user()->type == 'A')
        <a href="{{ route('listing.create')}}" class="btn btn-lg btn-primary">Create</a>
        @endif
        <br><br>

        <div class="row">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">List Name</th>
                  <th scope="col">Distance</th>
                  <th scope="col">User</th>
                  <th scope="col">Created At</th>
                  @if(Auth::user()->type == 'A')
                  <th>Action</th>
                  @endif
                </tr>
              </thead>
              <tbody>
                  @foreach ($lists as $list)
                      <tr>
                        <td>
                            <a href="{{ route('listing.show',$list->id)}}">{{ $list->list_name }}</a>
                        </td>
                        <td>{{ $list->distance }}</td>
                        <td>{{ $list->user->name }}</td>
                        <td>{{ $list->created_at }}</td>
                        @if(Auth::user()->type == 'A')
                        <td>
                            <form action="{{ route('listing.destroy',$list->id)}}" method="POST">
                                @csrf
                                @method('delete')

                                <a href="{{ route('listing.edit',$list->id)}}" class="btn btn-sm btn-warning">Edit</a>
                                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                            </form>
                        </td>
                        @endif
                      </tr>
                  @endforeach
              </tbody>
            </table>
        </div>
    </div>
@endsection

@section('script')
<script type="text/javascript">
        $(function(){

        // handle delete button click
        $('body').on('click', '.button-delete', function(e) {
        e.preventDefault();

        // get the id of the todo task
        var id = $(this).attr('data-id');

        // get csrf token value
        var csrf_token = $('meta[name="csrf-token"]').attr('content');

        // now make the ajax request
        $.ajax({
          'url': '/todo/' + id,
          'type': 'DELETE',
          headers: { 'X-CSRF-TOKEN': csrf_token }
        }).done(function() {
          console.log('Todo task deleted: ' + id);
          window.location = window.location.href;
        }).fail(function() {
          alert('something went wrong!');
        });

        });

        });
</script>
@endsection

resources/views/admin/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">{{ $listing->list_name }}</h5>
            <p class="card-text text-muted">The restaurant is {{ $listing->distance }} KM from your location.</p>
            <a href="{{ route('listing.index')}}" class="card-link btn-sm btn-primary">Back</a>
            @if(Auth::user()->type == 'A')
            <a href="{{ route('listing.edit',$listing)}}" class="card-link btn-sm btn-warning">Edit</a>
            @endif
          </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @yield('script')
</body>
</html>